Update to actions/cache v4.2.0 (#486)
I hope this will fix the presubmit which currently fails with:

Error: This request has been automatically failed because it uses a
deprecated version of `actions/cache:
6998d139ddd3e68c71e9e398d8e40b71a2f39812`. Please update your workflow
to use v3/v4 of actions/cache to avoid interruptions. Learn more:
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down