Revert "Allows TokenVendor to read SA from JWT.SUB (#539)" (#543)
This reverts commit 4d0c8f37913fe76400516c2c54dc059c67ca112f,
https://cloudlogging.app.goo.gl/M1JMPrN1rMJf37Y68

See https://cloudlogging.app.goo.gl/4rL1Y3WxtwGJLmiT9
```
Error: "service account "dev-ensonic1-c-googlers-com" not allowed"
message: "unable to retrieve cloud access token with given JWT"
```

Rollback tested on robco-ensonic:

![image](https://github.com/user-attachments/assets/6d6fd89b-ae15-44fc-8553-69693ee804e6)