Revert #222 (#226)
It causes the postsubmit integration test to fail with:

```
error: Timeout occurred
TEST FAILED: echo command did not run, output was "", want "hello"
```

when testing `kubectl exec`.


https://source.cloud.google.com/results/invocations/8f0b86f7-c5c4-41a3-9e4c-43e325d9e1ae/targets/%2F%2Fsrc%2Fgo%2Ftests:relay_test/log

- Revert "Use %v instead of %s in relay logs (#224)"
- Revert "fix leaking connections when user client closes connection
(#222)"